.github/workflows/ci-go-tests.yaml: Just try duplicating things for Windows.

diff --git a/.github/workflows/ci-go-tests.yaml b/.github/workflows/ci-go-tests.yaml
--- a/.github/workflows/ci-go-tests.yaml
+++ b/.github/workflows/ci-go-tests.yaml
@@ -44,11 +44,12 @@ jobs:
         path-type: inherit
         msystem: UCRT64
         pacboy: icu:p toolchain:p pkg-config:p
-    - name: Test All
+    - name: Test All (Windows)
       working-directory: ./go
-      shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash' }}
+      shell: msys2 {0}
+      if: ${{ matrix.os == 'windows-latest' }}
       run: |
-        files=$($GO list ./...)
+        files=$(go.exe list ./...)
         SAVEIFS=$IFS
         IFS=$'\n'
         file_arr=($files)
@@ -66,12 +67,12 @@ jobs:
           if [ "$MATRIX_OS" == 'ubuntu-22.04' ]
           then
             if [[ "${file_arr[$i]}" != *enginetest* ]]; then
-              $GO test -vet=off -timeout 45m -race "${file_arr[$i]}"
+              go.exe test -vet=off -timeout 45m -race "${file_arr[$i]}"
             else
               echo "skipping enginetests for -race"
             fi
           else
-            $GO test -vet=off -timeout 45m "${file_arr[$i]}"
+            go.exe test -vet=off -timeout 45m "${file_arr[$i]}"
           fi
           succeeded=$(echo "$?")
           if [ "$succeeded" -ne 0 ]; then
@@ -81,7 +82,43 @@ jobs:
         done
       env:
         MATRIX_OS: ${{ matrix.os }}
-        GO: ${{ matrix.os == 'windows-latest' && 'go.exe' || 'go' }}
+    - name: Test All (*nix)
+      working-directory: ./go
+      if: ${{ matrix.os != 'windows-latest' }}
+      run: |
+        files=$(go list ./...)
+        SAVEIFS=$IFS
+        IFS=$'\n'
+        file_arr=($files)
+        IFS=$SAVEIFS
+        
+        for (( i=0; i<${#file_arr[@]}; i++ ))
+        do
+          # Skip binlog tests as they run in a separate CI job
+          if [[ "${file_arr[$i]}" == *binlogreplication* ]]; then
+            echo "Skipping binlog package: ${file_arr[$i]} (runs in separate CI)"
+            continue
+          fi
+          
+          echo "Testing Package: ${file_arr[$i]}"
+          if [ "$MATRIX_OS" == 'ubuntu-22.04' ]
+          then
+            if [[ "${file_arr[$i]}" != *enginetest* ]]; then
+              go test -vet=off -timeout 45m -race "${file_arr[$i]}"
+            else
+              echo "skipping enginetests for -race"
+            fi
+          else
+            go test -vet=off -timeout 45m "${file_arr[$i]}"
+          fi
+          succeeded=$(echo "$?")
+          if [ "$succeeded" -ne 0 ]; then
+            echo "Testing failed in package ${file_arr[$i]}"
+            exit 1;
+          fi
+        done
+      env:
+        MATRIX_OS: ${{ matrix.os }}
   noracetest:
     name: Go tests - no race
     defaults:
@@ -113,12 +150,20 @@ jobs:
         path-type: inherit
         msystem: UCRT64
         pacboy: icu:p toolchain:p pkg-config:p
-    - name: Test All
+    - name: Test All (Windows)
       working-directory: ./go
-      shell: ${{ "$MATRIX_OS" == 'windows-latest' && 'msys2 {0}' || 'bash' }}
+      shell: msys2 {0}
+      if: ${{ matrix.os == 'windows-latest' }}
       run: |
-        $GO test -vet=off -timeout 30m ./libraries/doltcore/sqle/integration_test
+        go.exe test -vet=off -timeout 30m ./libraries/doltcore/sqle/integration_test
       env:
         MATRIX_OS: ${{ matrix.os }}
-        GO: ${{ "$MATRIX_OS" == 'windows-latest' && 'go.exe' || 'go' }}
+        DOLT_TEST_RUN_NON_RACE_TESTS: "true"
+    - name: Test All (*nix)
+      working-directory: ./go
+      if: ${{ matrix.os != 'windows-latest' }}
+      run: |
+        go test -vet=off -timeout 30m ./libraries/doltcore/sqle/integration_test
+      env:
+        MATRIX_OS: ${{ matrix.os }}
         DOLT_TEST_RUN_NON_RACE_TESTS: "true"
